packages:
  - "."
  - "../vibly-coordinator-http-contract"
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  bufferutil: true
  esbuild: true
  keccak: true
  sharp: true
  utf-8-validate: true
patchedDependencies:
  '@talismn/connect-components@1.1.9': patches/@talismn__connect-components@1.1.9.patch
