export const queryKeys = {
  health: ["health"] as const,
  projects: (networkId: string) => ["projects", networkId] as const,
  project: (networkId: string, projectId: string) => ["project", networkId, projectId] as const,
  objectives: (projectId: string) => ["objectives", projectId] as const,
  boundary: (projectId: string) => ["boundary", projectId] as const,
  principals: ["principals"] as const,
  agents: ["agents"] as const,
  runtimeBindings: (agentId: string) => ["runtime-bindings", agentId] as const,
  state: (projectId: string) => ["state", projectId] as const,
  knowledge: (projectId: string) => ["knowledge", projectId] as const,
  section: (projectId: string, section: string) => ["section", projectId, section] as const,
  projectOverview: (networkId: string, projectId: string) => ["project-overview", networkId, projectId] as const,
  projectTimeline: (networkId: string, projectId: string) => ["project-timeline", networkId, projectId] as const,
  traces: (networkId: string) => ["traces", networkId] as const,
  trace: (networkId: string, traceId: string) => ["trace", networkId, traceId] as const,
  events: (networkId: string, projectId: string) => ["events", networkId, projectId] as const,

  // V0.2 keys
  networkFeed: (networkId: string, limit?: number) => ["network-feed", networkId, limit ?? null] as const,
  feedEvent: (networkId: string, eventId: string) => ["feed-event", networkId, eventId] as const,
  networkOrganizations: (networkId: string, limit?: number) => ["network-organizations", networkId, limit ?? null] as const,
  networkOrganization: (networkId: string, orgId: string) => ["network-organization", networkId, orgId] as const,
  organizationFeed: (networkId: string, orgId: string, limit?: number) => ["organization-feed", networkId, orgId, limit ?? null] as const,
  networkAgents: (networkId: string, limit?: number) => ["network-agents", networkId, limit ?? null] as const,
  networkAgent: (networkId: string, agentId: string) => ["network-agent", networkId, agentId] as const,
  agentReputation: (networkId: string, agentId: string) => ["agent-reputation", networkId, agentId] as const,
  personalCenter: (networkId: string) => ["personal-center", networkId] as const,
  agentRewards: (networkId: string, principalId?: string | null) => ["agent-rewards", networkId, principalId ?? null] as const,
  rewardDays: (networkId: string, limit?: number) => ["reward-days", networkId, limit ?? null] as const,
  taskRewards: (networkId: string, taskId?: string | null, principalId?: string | null) => ["task-rewards", networkId, taskId ?? null, principalId ?? null] as const,
  guardianDecision: (networkId: string, accountId: string) => ["guardian-decision", networkId, accountId] as const,
  observationV2: (networkId: string, id: string) => ["observation-v2", networkId, id] as const,
  proposalV2: (networkId: string, id: string) => ["proposal-v2", networkId, id] as const,
  votingRoundV2: (networkId: string, id: string) => ["voting-round-v2", networkId, id] as const,
  mechanismV2: (networkId: string, id: string) => ["mechanism-v2", networkId, id] as const,
  taskV2: (networkId: string, id: string) => ["task-v2", networkId, id] as const,
  artifactV2: (networkId: string, id: string) => ["artifact-v2", networkId, id] as const,
  discussionV2: (networkId: string, id: string) => ["discussion-v2", networkId, id] as const,
  guardianRequests: (networkId: string) => ["guardian-requests", networkId] as const,
  getVibConfig: (networkId: string) => ["get-vib", networkId, "config"] as const,
  getVibQuote: (networkId: string, amount: string) => ["get-vib", networkId, "quote", amount] as const,
  getVibSummary: (networkId: string, accountId: string) => ["get-vib", networkId, "summary", accountId] as const,
  getVibProof: (networkId: string, accountId: string) => ["get-vib", networkId, "proof", accountId] as const,
  getVibRecords: (networkId: string, accountId: string) => ["get-vib", networkId, "records", accountId] as const,
  getVibCurve: (networkId: string) => ["get-vib", networkId, "curve"] as const,
};
