export const queryKeys = {
  health: ["health"] as const,
  projects: ["projects"] as const,
  project: (projectId: string) => ["project", projectId] as const,
  objectives: (projectId: string) => ["objectives", projectId] as const,
  boundary: (projectId: string) => ["boundary", projectId] as const,
  principals: ["principals"] as const,
  agents: ["agents"] as const,
  runtimeBindings: (agentId: string) => ["runtime-bindings", agentId] as const,
  state: (projectId: string) => ["state", projectId] as const,
  knowledge: (projectId: string) => ["knowledge", projectId] as const,
  section: (projectId: string, section: string) => ["section", projectId, section] as const,
  projectOverview: (projectId: string) => ["project-overview", projectId] as const,
  projectTimeline: (projectId: string) => ["project-timeline", projectId] as const,
  traces: ["traces"] as const,
  trace: (traceId: string) => ["trace", traceId] as const,
  events: (projectId: string) => ["events", projectId] as const,

  // V0.2 keys
  networkFeed: (limit?: number) => ["network-feed", limit ?? null] as const,
  feedEvent: (eventId: string) => ["feed-event", eventId] as const,
  networkOrganizations: (limit?: number) => ["network-organizations", limit ?? null] as const,
  networkOrganization: (orgId: string) => ["network-organization", orgId] as const,
  organizationFeed: (orgId: string, limit?: number) => ["organization-feed", orgId, limit ?? null] as const,
  networkAgents: (limit?: number) => ["network-agents", limit ?? null] as const,
  networkAgent: (agentId: string) => ["network-agent", agentId] as const,
  agentReputation: (agentId: string) => ["agent-reputation", agentId] as const,
  personalCenter: ["personal-center"] as const,
  observationV2: (id: string) => ["observation-v2", id] as const,
  proposalV2: (id: string) => ["proposal-v2", id] as const,
  votingRoundV2: (id: string) => ["voting-round-v2", id] as const,
  mechanismV2: (id: string) => ["mechanism-v2", id] as const,
  taskV2: (id: string) => ["task-v2", id] as const,
  artifactV2: (id: string) => ["artifact-v2", id] as const,
  discussionV2: (id: string) => ["discussion-v2", id] as const,
  guardianRequests: ["guardian-requests"] as const,
};
